/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiChatRouteImport } from './routes/ai-chat'
import { Route as AiNotesRouteImport } from './routes/ai-notes'
import { Route as AiQuizRouteImport } from './routes/ai-quiz'
import { Route as AiSummarizerRouteImport } from './routes/ai-summarizer'
import { Route as CompressPdfRouteImport } from './routes/compress-pdf'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DeletePdfPagesRouteImport } from './routes/delete-pdf-pages'
import { Route as ExtractPdfPagesRouteImport } from './routes/extract-pdf-pages'
import { Route as JpgToPdfRouteImport } from './routes/jpg-to-pdf'
import { Route as MergePdfRouteImport } from './routes/merge-pdf'
import { Route as PdfToJpgRouteImport } from './routes/pdf-to-jpg'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RotatePdfRouteImport } from './routes/rotate-pdf'
import { Route as SplitPdfRouteImport } from './routes/split-pdf'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ToolsRouteImport } from './routes/tools'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatRoute = AiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AiNotesRoute = AiNotesRouteImport.update({
  id: '/ai-notes',
  path: '/ai-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const AiQuizRoute = AiQuizRouteImport.update({
  id: '/ai-quiz',
  path: '/ai-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSummarizerRoute = AiSummarizerRouteImport.update({
  id: '/ai-summarizer',
  path: '/ai-summarizer',
  getParentRoute: () => rootRouteImport,
} as any)
const CompressPdfRoute = CompressPdfRouteImport.update({
  id: '/compress-pdf',
  path: '/compress-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DeletePdfPagesRoute = DeletePdfPagesRouteImport.update({
  id: '/delete-pdf-pages',
  path: '/delete-pdf-pages',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtractPdfPagesRoute = ExtractPdfPagesRouteImport.update({
  id: '/extract-pdf-pages',
  path: '/extract-pdf-pages',
  getParentRoute: () => rootRouteImport,
} as any)
const JpgToPdfRoute = JpgToPdfRouteImport.update({
  id: '/jpg-to-pdf',
  path: '/jpg-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const MergePdfRoute = MergePdfRouteImport.update({
  id: '/merge-pdf',
  path: '/merge-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToJpgRoute = PdfToJpgRouteImport.update({
  id: '/pdf-to-jpg',
  path: '/pdf-to-jpg',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RotatePdfRoute = RotatePdfRouteImport.update({
  id: '/rotate-pdf',
  path: '/rotate-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitPdfRoute = SplitPdfRouteImport.update({
  id: '/split-pdf',
  path: '/split-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-chat': typeof AiChatRoute
  '/ai-notes': typeof AiNotesRoute
  '/ai-quiz': typeof AiQuizRoute
  '/ai-summarizer': typeof AiSummarizerRoute
  '/compress-pdf': typeof CompressPdfRoute
  '/contact': typeof ContactRoute
  '/delete-pdf-pages': typeof DeletePdfPagesRoute
  '/extract-pdf-pages': typeof ExtractPdfPagesRoute
  '/jpg-to-pdf': typeof JpgToPdfRoute
  '/merge-pdf': typeof MergePdfRoute
  '/pdf-to-jpg': typeof PdfToJpgRoute
  '/privacy': typeof PrivacyRoute
  '/rotate-pdf': typeof RotatePdfRoute
  '/split-pdf': typeof SplitPdfRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-chat': typeof AiChatRoute
  '/ai-notes': typeof AiNotesRoute
  '/ai-quiz': typeof AiQuizRoute
  '/ai-summarizer': typeof AiSummarizerRoute
  '/compress-pdf': typeof CompressPdfRoute
  '/contact': typeof ContactRoute
  '/delete-pdf-pages': typeof DeletePdfPagesRoute
  '/extract-pdf-pages': typeof ExtractPdfPagesRoute
  '/jpg-to-pdf': typeof JpgToPdfRoute
  '/merge-pdf': typeof MergePdfRoute
  '/pdf-to-jpg': typeof PdfToJpgRoute
  '/privacy': typeof PrivacyRoute
  '/rotate-pdf': typeof RotatePdfRoute
  '/split-pdf': typeof SplitPdfRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-chat': typeof AiChatRoute
  '/ai-notes': typeof AiNotesRoute
  '/ai-quiz': typeof AiQuizRoute
  '/ai-summarizer': typeof AiSummarizerRoute
  '/compress-pdf': typeof CompressPdfRoute
  '/contact': typeof ContactRoute
  '/delete-pdf-pages': typeof DeletePdfPagesRoute
  '/extract-pdf-pages': typeof ExtractPdfPagesRoute
  '/jpg-to-pdf': typeof JpgToPdfRoute
  '/merge-pdf': typeof MergePdfRoute
  '/pdf-to-jpg': typeof PdfToJpgRoute
  '/privacy': typeof PrivacyRoute
  '/rotate-pdf': typeof RotatePdfRoute
  '/split-pdf': typeof SplitPdfRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-chat'
    | '/ai-notes'
    | '/ai-quiz'
    | '/ai-summarizer'
    | '/compress-pdf'
    | '/contact'
    | '/delete-pdf-pages'
    | '/extract-pdf-pages'
    | '/jpg-to-pdf'
    | '/merge-pdf'
    | '/pdf-to-jpg'
    | '/privacy'
    | '/rotate-pdf'
    | '/split-pdf'
    | '/terms'
    | '/tools'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-chat'
    | '/ai-notes'
    | '/ai-quiz'
    | '/ai-summarizer'
    | '/compress-pdf'
    | '/contact'
    | '/delete-pdf-pages'
    | '/extract-pdf-pages'
    | '/jpg-to-pdf'
    | '/merge-pdf'
    | '/pdf-to-jpg'
    | '/privacy'
    | '/rotate-pdf'
    | '/split-pdf'
    | '/terms'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/ai-chat'
    | '/ai-notes'
    | '/ai-quiz'
    | '/ai-summarizer'
    | '/compress-pdf'
    | '/contact'
    | '/delete-pdf-pages'
    | '/extract-pdf-pages'
    | '/jpg-to-pdf'
    | '/merge-pdf'
    | '/pdf-to-jpg'
    | '/privacy'
    | '/rotate-pdf'
    | '/split-pdf'
    | '/terms'
    | '/tools'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiChatRoute: typeof AiChatRoute
  AiNotesRoute: typeof AiNotesRoute
  AiQuizRoute: typeof AiQuizRoute
  AiSummarizerRoute: typeof AiSummarizerRoute
  CompressPdfRoute: typeof CompressPdfRoute
  ContactRoute: typeof ContactRoute
  DeletePdfPagesRoute: typeof DeletePdfPagesRoute
  ExtractPdfPagesRoute: typeof ExtractPdfPagesRoute
  JpgToPdfRoute: typeof JpgToPdfRoute
  MergePdfRoute: typeof MergePdfRoute
  PdfToJpgRoute: typeof PdfToJpgRoute
  PrivacyRoute: typeof PrivacyRoute
  RotatePdfRoute: typeof RotatePdfRoute
  SplitPdfRoute: typeof SplitPdfRoute
  TermsRoute: typeof TermsRoute
  ToolsRoute: typeof ToolsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-chat': {
      id: '/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-notes': {
      id: '/ai-notes'
      path: '/ai-notes'
      fullPath: '/ai-notes'
      preLoaderRoute: typeof AiNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-quiz': {
      id: '/ai-quiz'
      path: '/ai-quiz'
      fullPath: '/ai-quiz'
      preLoaderRoute: typeof AiQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-summarizer': {
      id: '/ai-summarizer'
      path: '/ai-summarizer'
      fullPath: '/ai-summarizer'
      preLoaderRoute: typeof AiSummarizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compress-pdf': {
      id: '/compress-pdf'
      path: '/compress-pdf'
      fullPath: '/compress-pdf'
      preLoaderRoute: typeof CompressPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-pdf-pages': {
      id: '/delete-pdf-pages'
      path: '/delete-pdf-pages'
      fullPath: '/delete-pdf-pages'
      preLoaderRoute: typeof DeletePdfPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extract-pdf-pages': {
      id: '/extract-pdf-pages'
      path: '/extract-pdf-pages'
      fullPath: '/extract-pdf-pages'
      preLoaderRoute: typeof ExtractPdfPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jpg-to-pdf': {
      id: '/jpg-to-pdf'
      path: '/jpg-to-pdf'
      fullPath: '/jpg-to-pdf'
      preLoaderRoute: typeof JpgToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merge-pdf': {
      id: '/merge-pdf'
      path: '/merge-pdf'
      fullPath: '/merge-pdf'
      preLoaderRoute: typeof MergePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-to-jpg': {
      id: '/pdf-to-jpg'
      path: '/pdf-to-jpg'
      fullPath: '/pdf-to-jpg'
      preLoaderRoute: typeof PdfToJpgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rotate-pdf': {
      id: '/rotate-pdf'
      path: '/rotate-pdf'
      fullPath: '/rotate-pdf'
      preLoaderRoute: typeof RotatePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/split-pdf': {
      id: '/split-pdf'
      path: '/split-pdf'
      fullPath: '/split-pdf'
      preLoaderRoute: typeof SplitPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiChatRoute: AiChatRoute,
  AiNotesRoute: AiNotesRoute,
  AiQuizRoute: AiQuizRoute,
  AiSummarizerRoute: AiSummarizerRoute,
  CompressPdfRoute: CompressPdfRoute,
  ContactRoute: ContactRoute,
  DeletePdfPagesRoute: DeletePdfPagesRoute,
  ExtractPdfPagesRoute: ExtractPdfPagesRoute,
  JpgToPdfRoute: JpgToPdfRoute,
  MergePdfRoute: MergePdfRoute,
  PdfToJpgRoute: PdfToJpgRoute,
  PrivacyRoute: PrivacyRoute,
  RotatePdfRoute: RotatePdfRoute,
  SplitPdfRoute: SplitPdfRoute,
  TermsRoute: TermsRoute,
  ToolsRoute: ToolsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
